# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/cmake

# The command to remove a file.
RM = /cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /afs/cern.ch/user/a/ahau/Par04

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /afs/cern.ch/user/a/ahau/Par04

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc10-opt/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/cern.ch/user/a/ahau/Par04/CMakeFiles /afs/cern.ch/user/a/ahau/Par04//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/cern.ch/user/a/ahau/Par04/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Par04

# Build rule for target.
Par04: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Par04
.PHONY : Par04

# fast build rule for target.
Par04/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Par04.dir/build.make CMakeFiles/Par04.dir/build
.PHONY : Par04/fast

#=============================================================================
# Target rules for targets named examplePar04onnxdata

# Build rule for target.
examplePar04onnxdata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examplePar04onnxdata
.PHONY : examplePar04onnxdata

# fast build rule for target.
examplePar04onnxdata/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04onnxdata.dir/build.make CMakeFiles/examplePar04onnxdata.dir/build
.PHONY : examplePar04onnxdata/fast

#=============================================================================
# Target rules for targets named examplePar04lwtnndata

# Build rule for target.
examplePar04lwtnndata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examplePar04lwtnndata
.PHONY : examplePar04lwtnndata

# fast build rule for target.
examplePar04lwtnndata/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04lwtnndata.dir/build.make CMakeFiles/examplePar04lwtnndata.dir/build
.PHONY : examplePar04lwtnndata/fast

#=============================================================================
# Target rules for targets named examplePar04

# Build rule for target.
examplePar04: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examplePar04
.PHONY : examplePar04

# fast build rule for target.
examplePar04/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/build
.PHONY : examplePar04/fast

examplePar04.o: examplePar04.cc.o
.PHONY : examplePar04.o

# target to build an object file
examplePar04.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/examplePar04.cc.o
.PHONY : examplePar04.cc.o

examplePar04.i: examplePar04.cc.i
.PHONY : examplePar04.i

# target to preprocess a source file
examplePar04.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/examplePar04.cc.i
.PHONY : examplePar04.cc.i

examplePar04.s: examplePar04.cc.s
.PHONY : examplePar04.s

# target to generate assembly for a file
examplePar04.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/examplePar04.cc.s
.PHONY : examplePar04.cc.s

src/Par04ActionInitialisation.o: src/Par04ActionInitialisation.cc.o
.PHONY : src/Par04ActionInitialisation.o

# target to build an object file
src/Par04ActionInitialisation.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04ActionInitialisation.cc.o
.PHONY : src/Par04ActionInitialisation.cc.o

src/Par04ActionInitialisation.i: src/Par04ActionInitialisation.cc.i
.PHONY : src/Par04ActionInitialisation.i

# target to preprocess a source file
src/Par04ActionInitialisation.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04ActionInitialisation.cc.i
.PHONY : src/Par04ActionInitialisation.cc.i

src/Par04ActionInitialisation.s: src/Par04ActionInitialisation.cc.s
.PHONY : src/Par04ActionInitialisation.s

# target to generate assembly for a file
src/Par04ActionInitialisation.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04ActionInitialisation.cc.s
.PHONY : src/Par04ActionInitialisation.cc.s

src/Par04DefineMeshModel.o: src/Par04DefineMeshModel.cc.o
.PHONY : src/Par04DefineMeshModel.o

# target to build an object file
src/Par04DefineMeshModel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04DefineMeshModel.cc.o
.PHONY : src/Par04DefineMeshModel.cc.o

src/Par04DefineMeshModel.i: src/Par04DefineMeshModel.cc.i
.PHONY : src/Par04DefineMeshModel.i

# target to preprocess a source file
src/Par04DefineMeshModel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04DefineMeshModel.cc.i
.PHONY : src/Par04DefineMeshModel.cc.i

src/Par04DefineMeshModel.s: src/Par04DefineMeshModel.cc.s
.PHONY : src/Par04DefineMeshModel.s

# target to generate assembly for a file
src/Par04DefineMeshModel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04DefineMeshModel.cc.s
.PHONY : src/Par04DefineMeshModel.cc.s

src/Par04DetectorConstruction.o: src/Par04DetectorConstruction.cc.o
.PHONY : src/Par04DetectorConstruction.o

# target to build an object file
src/Par04DetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04DetectorConstruction.cc.o
.PHONY : src/Par04DetectorConstruction.cc.o

src/Par04DetectorConstruction.i: src/Par04DetectorConstruction.cc.i
.PHONY : src/Par04DetectorConstruction.i

# target to preprocess a source file
src/Par04DetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04DetectorConstruction.cc.i
.PHONY : src/Par04DetectorConstruction.cc.i

src/Par04DetectorConstruction.s: src/Par04DetectorConstruction.cc.s
.PHONY : src/Par04DetectorConstruction.s

# target to generate assembly for a file
src/Par04DetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04DetectorConstruction.cc.s
.PHONY : src/Par04DetectorConstruction.cc.s

src/Par04DetectorMessenger.o: src/Par04DetectorMessenger.cc.o
.PHONY : src/Par04DetectorMessenger.o

# target to build an object file
src/Par04DetectorMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04DetectorMessenger.cc.o
.PHONY : src/Par04DetectorMessenger.cc.o

src/Par04DetectorMessenger.i: src/Par04DetectorMessenger.cc.i
.PHONY : src/Par04DetectorMessenger.i

# target to preprocess a source file
src/Par04DetectorMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04DetectorMessenger.cc.i
.PHONY : src/Par04DetectorMessenger.cc.i

src/Par04DetectorMessenger.s: src/Par04DetectorMessenger.cc.s
.PHONY : src/Par04DetectorMessenger.s

# target to generate assembly for a file
src/Par04DetectorMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04DetectorMessenger.cc.s
.PHONY : src/Par04DetectorMessenger.cc.s

src/Par04EventAction.o: src/Par04EventAction.cc.o
.PHONY : src/Par04EventAction.o

# target to build an object file
src/Par04EventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04EventAction.cc.o
.PHONY : src/Par04EventAction.cc.o

src/Par04EventAction.i: src/Par04EventAction.cc.i
.PHONY : src/Par04EventAction.i

# target to preprocess a source file
src/Par04EventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04EventAction.cc.i
.PHONY : src/Par04EventAction.cc.i

src/Par04EventAction.s: src/Par04EventAction.cc.s
.PHONY : src/Par04EventAction.s

# target to generate assembly for a file
src/Par04EventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04EventAction.cc.s
.PHONY : src/Par04EventAction.cc.s

src/Par04EventInformation.o: src/Par04EventInformation.cc.o
.PHONY : src/Par04EventInformation.o

# target to build an object file
src/Par04EventInformation.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04EventInformation.cc.o
.PHONY : src/Par04EventInformation.cc.o

src/Par04EventInformation.i: src/Par04EventInformation.cc.i
.PHONY : src/Par04EventInformation.i

# target to preprocess a source file
src/Par04EventInformation.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04EventInformation.cc.i
.PHONY : src/Par04EventInformation.cc.i

src/Par04EventInformation.s: src/Par04EventInformation.cc.s
.PHONY : src/Par04EventInformation.s

# target to generate assembly for a file
src/Par04EventInformation.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04EventInformation.cc.s
.PHONY : src/Par04EventInformation.cc.s

src/Par04Hit.o: src/Par04Hit.cc.o
.PHONY : src/Par04Hit.o

# target to build an object file
src/Par04Hit.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04Hit.cc.o
.PHONY : src/Par04Hit.cc.o

src/Par04Hit.i: src/Par04Hit.cc.i
.PHONY : src/Par04Hit.i

# target to preprocess a source file
src/Par04Hit.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04Hit.cc.i
.PHONY : src/Par04Hit.cc.i

src/Par04Hit.s: src/Par04Hit.cc.s
.PHONY : src/Par04Hit.s

# target to generate assembly for a file
src/Par04Hit.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04Hit.cc.s
.PHONY : src/Par04Hit.cc.s

src/Par04InferenceMessenger.o: src/Par04InferenceMessenger.cc.o
.PHONY : src/Par04InferenceMessenger.o

# target to build an object file
src/Par04InferenceMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04InferenceMessenger.cc.o
.PHONY : src/Par04InferenceMessenger.cc.o

src/Par04InferenceMessenger.i: src/Par04InferenceMessenger.cc.i
.PHONY : src/Par04InferenceMessenger.i

# target to preprocess a source file
src/Par04InferenceMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04InferenceMessenger.cc.i
.PHONY : src/Par04InferenceMessenger.cc.i

src/Par04InferenceMessenger.s: src/Par04InferenceMessenger.cc.s
.PHONY : src/Par04InferenceMessenger.s

# target to generate assembly for a file
src/Par04InferenceMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04InferenceMessenger.cc.s
.PHONY : src/Par04InferenceMessenger.cc.s

src/Par04InferenceSetup.o: src/Par04InferenceSetup.cc.o
.PHONY : src/Par04InferenceSetup.o

# target to build an object file
src/Par04InferenceSetup.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04InferenceSetup.cc.o
.PHONY : src/Par04InferenceSetup.cc.o

src/Par04InferenceSetup.i: src/Par04InferenceSetup.cc.i
.PHONY : src/Par04InferenceSetup.i

# target to preprocess a source file
src/Par04InferenceSetup.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04InferenceSetup.cc.i
.PHONY : src/Par04InferenceSetup.cc.i

src/Par04InferenceSetup.s: src/Par04InferenceSetup.cc.s
.PHONY : src/Par04InferenceSetup.s

# target to generate assembly for a file
src/Par04InferenceSetup.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04InferenceSetup.cc.s
.PHONY : src/Par04InferenceSetup.cc.s

src/Par04LwtnnInference.o: src/Par04LwtnnInference.cc.o
.PHONY : src/Par04LwtnnInference.o

# target to build an object file
src/Par04LwtnnInference.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04LwtnnInference.cc.o
.PHONY : src/Par04LwtnnInference.cc.o

src/Par04LwtnnInference.i: src/Par04LwtnnInference.cc.i
.PHONY : src/Par04LwtnnInference.i

# target to preprocess a source file
src/Par04LwtnnInference.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04LwtnnInference.cc.i
.PHONY : src/Par04LwtnnInference.cc.i

src/Par04LwtnnInference.s: src/Par04LwtnnInference.cc.s
.PHONY : src/Par04LwtnnInference.s

# target to generate assembly for a file
src/Par04LwtnnInference.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04LwtnnInference.cc.s
.PHONY : src/Par04LwtnnInference.cc.s

src/Par04MLFastSimModel.o: src/Par04MLFastSimModel.cc.o
.PHONY : src/Par04MLFastSimModel.o

# target to build an object file
src/Par04MLFastSimModel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04MLFastSimModel.cc.o
.PHONY : src/Par04MLFastSimModel.cc.o

src/Par04MLFastSimModel.i: src/Par04MLFastSimModel.cc.i
.PHONY : src/Par04MLFastSimModel.i

# target to preprocess a source file
src/Par04MLFastSimModel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04MLFastSimModel.cc.i
.PHONY : src/Par04MLFastSimModel.cc.i

src/Par04MLFastSimModel.s: src/Par04MLFastSimModel.cc.s
.PHONY : src/Par04MLFastSimModel.s

# target to generate assembly for a file
src/Par04MLFastSimModel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04MLFastSimModel.cc.s
.PHONY : src/Par04MLFastSimModel.cc.s

src/Par04OnnxInference.o: src/Par04OnnxInference.cc.o
.PHONY : src/Par04OnnxInference.o

# target to build an object file
src/Par04OnnxInference.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04OnnxInference.cc.o
.PHONY : src/Par04OnnxInference.cc.o

src/Par04OnnxInference.i: src/Par04OnnxInference.cc.i
.PHONY : src/Par04OnnxInference.i

# target to preprocess a source file
src/Par04OnnxInference.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04OnnxInference.cc.i
.PHONY : src/Par04OnnxInference.cc.i

src/Par04OnnxInference.s: src/Par04OnnxInference.cc.s
.PHONY : src/Par04OnnxInference.s

# target to generate assembly for a file
src/Par04OnnxInference.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04OnnxInference.cc.s
.PHONY : src/Par04OnnxInference.cc.s

src/Par04PrimaryGeneratorAction.o: src/Par04PrimaryGeneratorAction.cc.o
.PHONY : src/Par04PrimaryGeneratorAction.o

# target to build an object file
src/Par04PrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04PrimaryGeneratorAction.cc.o
.PHONY : src/Par04PrimaryGeneratorAction.cc.o

src/Par04PrimaryGeneratorAction.i: src/Par04PrimaryGeneratorAction.cc.i
.PHONY : src/Par04PrimaryGeneratorAction.i

# target to preprocess a source file
src/Par04PrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04PrimaryGeneratorAction.cc.i
.PHONY : src/Par04PrimaryGeneratorAction.cc.i

src/Par04PrimaryGeneratorAction.s: src/Par04PrimaryGeneratorAction.cc.s
.PHONY : src/Par04PrimaryGeneratorAction.s

# target to generate assembly for a file
src/Par04PrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04PrimaryGeneratorAction.cc.s
.PHONY : src/Par04PrimaryGeneratorAction.cc.s

src/Par04RunAction.o: src/Par04RunAction.cc.o
.PHONY : src/Par04RunAction.o

# target to build an object file
src/Par04RunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04RunAction.cc.o
.PHONY : src/Par04RunAction.cc.o

src/Par04RunAction.i: src/Par04RunAction.cc.i
.PHONY : src/Par04RunAction.i

# target to preprocess a source file
src/Par04RunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04RunAction.cc.i
.PHONY : src/Par04RunAction.cc.i

src/Par04RunAction.s: src/Par04RunAction.cc.s
.PHONY : src/Par04RunAction.s

# target to generate assembly for a file
src/Par04RunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04RunAction.cc.s
.PHONY : src/Par04RunAction.cc.s

src/Par04SensitiveDetector.o: src/Par04SensitiveDetector.cc.o
.PHONY : src/Par04SensitiveDetector.o

# target to build an object file
src/Par04SensitiveDetector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04SensitiveDetector.cc.o
.PHONY : src/Par04SensitiveDetector.cc.o

src/Par04SensitiveDetector.i: src/Par04SensitiveDetector.cc.i
.PHONY : src/Par04SensitiveDetector.i

# target to preprocess a source file
src/Par04SensitiveDetector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04SensitiveDetector.cc.i
.PHONY : src/Par04SensitiveDetector.cc.i

src/Par04SensitiveDetector.s: src/Par04SensitiveDetector.cc.s
.PHONY : src/Par04SensitiveDetector.s

# target to generate assembly for a file
src/Par04SensitiveDetector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examplePar04.dir/build.make CMakeFiles/examplePar04.dir/src/Par04SensitiveDetector.cc.s
.PHONY : src/Par04SensitiveDetector.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Par04"
	@echo "... examplePar04lwtnndata"
	@echo "... examplePar04onnxdata"
	@echo "... examplePar04"
	@echo "... examplePar04.o"
	@echo "... examplePar04.i"
	@echo "... examplePar04.s"
	@echo "... src/Par04ActionInitialisation.o"
	@echo "... src/Par04ActionInitialisation.i"
	@echo "... src/Par04ActionInitialisation.s"
	@echo "... src/Par04DefineMeshModel.o"
	@echo "... src/Par04DefineMeshModel.i"
	@echo "... src/Par04DefineMeshModel.s"
	@echo "... src/Par04DetectorConstruction.o"
	@echo "... src/Par04DetectorConstruction.i"
	@echo "... src/Par04DetectorConstruction.s"
	@echo "... src/Par04DetectorMessenger.o"
	@echo "... src/Par04DetectorMessenger.i"
	@echo "... src/Par04DetectorMessenger.s"
	@echo "... src/Par04EventAction.o"
	@echo "... src/Par04EventAction.i"
	@echo "... src/Par04EventAction.s"
	@echo "... src/Par04EventInformation.o"
	@echo "... src/Par04EventInformation.i"
	@echo "... src/Par04EventInformation.s"
	@echo "... src/Par04Hit.o"
	@echo "... src/Par04Hit.i"
	@echo "... src/Par04Hit.s"
	@echo "... src/Par04InferenceMessenger.o"
	@echo "... src/Par04InferenceMessenger.i"
	@echo "... src/Par04InferenceMessenger.s"
	@echo "... src/Par04InferenceSetup.o"
	@echo "... src/Par04InferenceSetup.i"
	@echo "... src/Par04InferenceSetup.s"
	@echo "... src/Par04LwtnnInference.o"
	@echo "... src/Par04LwtnnInference.i"
	@echo "... src/Par04LwtnnInference.s"
	@echo "... src/Par04MLFastSimModel.o"
	@echo "... src/Par04MLFastSimModel.i"
	@echo "... src/Par04MLFastSimModel.s"
	@echo "... src/Par04OnnxInference.o"
	@echo "... src/Par04OnnxInference.i"
	@echo "... src/Par04OnnxInference.s"
	@echo "... src/Par04PrimaryGeneratorAction.o"
	@echo "... src/Par04PrimaryGeneratorAction.i"
	@echo "... src/Par04PrimaryGeneratorAction.s"
	@echo "... src/Par04RunAction.o"
	@echo "... src/Par04RunAction.i"
	@echo "... src/Par04RunAction.s"
	@echo "... src/Par04SensitiveDetector.o"
	@echo "... src/Par04SensitiveDetector.i"
	@echo "... src/Par04SensitiveDetector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

